---
- name: Installing httpd
  hosts: webservers
  remote_user: root 

  tasks:
  - name: HTTPD installation
    yum:
      name: httpd
      state: present 

  - name: Start the service 
    service:
      name: httpd
      state: started
  

  